export const dummyAppointments = [
    {
      appointment_id: 1,
      customer_id: 1,
      location_id: 101,
      date_and_time: '2023-07-25 09:00:00',
      service_group_id: 201,
      employee_group_id: 301,
      cost: 150.0,
      completion_status: 'Completed',
      payment_status: 'Paid',
      frequency_in_days: 30,
      followup_appointment: '2023-08-25 09:00:00',
      followup_reason: 'Regular checkup',
      notes: 'Performed pest control service at customer location.',
    },
    {
      appointment_id: 2,
      customer_id: 2,
      location_id: 102,
      date_and_time: '2023-07-26 10:30:00',
      service_group_id: 202,
      employee_group_id: 302,
      cost: 180.0,
      completion_status: 'Scheduled',
      payment_status: 'Unpaid',
      frequency_in_days: 60,
      followup_appointment: '2023-09-25 10:30:00',
      followup_reason: 'Special treatment required',
      notes: 'Upcoming appointment for pest inspection.',
    },
    {
      appointment_id: 3,
      customer_id: 3,
      location_id: 103,
      date_and_time: '2023-07-27 13:45:00',
      service_group_id: 203,
      employee_group_id: 303,
      cost: 200.0,
      completion_status: 'In Progress',
      payment_status: 'Unpaid',
      frequency_in_days: 90,
      followup_appointment: '2023-10-25 13:45:00',
      followup_reason: 'Large-scale pest treatment',
      notes: 'Ongoing pest eradication service.',
    },
    // Add more dummy appointments here...
  ];
  