export const dummyLocations = [
    {
      id: 1,
      customer_id: 1,
      address_line1: '123 Main Street',
      address_line2: 'Apt 456',
      state: 'Stateland',
      city: 'Cityville',
      postal_code: '12345',
      primary_contact: 'John Doe',
      secondary_contact: 'Jane Smith',
      notes: 'Headquarters',
    },
    {
      id: 2,
      customer_id: 2,
      address_line1: '456 Park Avenue',
      address_line2: 'Suite 789',
      state: 'Stateland',
      city: 'Townsville',
      postal_code: '56789',
      primary_contact: 'Jane Smith',
      secondary_contact: 'John Doe',
      notes: 'Branch Office',
    },
    {
      id: 3,
      customer_id: 1,
      address_line1: '789 Elm Road',
      address_line2: 'Unit 101',
      state: 'Stateland',
      city: 'Cityville',
      postal_code: '12345',
      primary_contact: 'Robert Johnson',
      secondary_contact: 'Emily Wilson',
      notes: 'Warehouse',
    },
    // Add more dummy locations here...
  ];
  